### ISSUE TITLE
Can a run consist only of events?

### ISSUE THREAD

**Issue by skyqrose** [cal-itp/operational-data-standard#11]
I couldn't attend the recent meeting about the ODS spec, but I watched the recording, and have some lingering questions. I hope I'm not too late for them.

Is it possible for a run or a piece to just consist of events, and not contain any trips or deadheads? I could imagine this being useful if someone wanted to use ODS to include schedules for operators on a cover list, operators who are assigned to run-as-directed, or for other employees like yard staff, maintenance workers, or supervisors. The spec as written does not make this clear.

In particular, when `runs_pieces.start/end_type` is `2` (Event), or when a run doesn't have any trips, should `runs_pieces.start/end_trip_id` also be able to reference `run_events.run_event_id`, or should the column be optional?

See also #12 (Include service_id in runs_pieces.txt to support non-unique run_ids?) where a run with no trips might need to be handled differently.

[Link to the spec, for convenience.](https://docs.calitp.org/operational-data-standard/spec/#runs)

**Comment by skyqrose** [comment]
Relatedly, it might be useful to represent breaks between two pieces as a run_event in ODS (to indicate for example whether the break is paid or unpaid). Should that run_event be at the end of the first piece, the beginning of the second piece, or should it get its own separate piece without any trips in it?

**Comment by skyqrose** [comment]
> I would like to hear more about the "run-as-directed" case

By run-as-directed, I mean the operator is scheduled to show up and run revenue service, but without a set schedule. An official (either in dispatch or at the terminal) would decide in the moment when to start each trip. This is useful for headway-based service. An example of when MBTA has had run-as-directed runs scheduled is when [a scheduled bridge closure](https://www.mbta.com/projects/commonwealth-avenue-bridge-replacement#) cut one of our light rail routes in two. The short end of the route was scheduled as run-as-directed for the duration of the closure. We also have a handful of operators with run-as-directed pieces in the schedule whose purpose I don't quite understand (I don't think they're the cover list), but I'd want to be able to represent them in ODS.

> we have runs as being made up of 1 or more pieces, and we defined a piece (at least verbally) as being everything between an employee getting on a vehicle and getting off the same vehicle

I don't like the "same vehicle" restriction. On the MBTA Green Line, vehicle assignments are very ad hoc, and operators often swap vehicles between every trip. Even on a more organized agency, if they do dropbacks, operators wouldn't end up on the same vehicle. I think of a piece as a consecutive period of time when you're getting paid for assigned work (i.e. not on break), regardless of what sorts of trips/layovers/tasks are scheduled for you during that time.

**Comment by skyqrose** [comment]
I'm also just realizing that I don't know if there's a way in the current spec to associate trips with runs (though I could just be confused here). Like, given a run, how do you get a list of trips, or given a trip, how do you find out what run it's on? `trips.txt` and `deadheads.txt` don't have a `run` field, and in the run tables there's no list of trips. I guess there's the `runs_pieces.txt:start_trip_id`, and you could look at that trip and its block, and assume that all trips on that block belong to the run. But that's complicated, and as mentioned in the previous comment, I wouldn't want to rely on that.

A table that would allow associating trips and runs straightforwardly would be just a big list of trip_id and run_id pairs, something like:
- schedule_id,
- run_id,
- trip/deadhead/event type (1, 2, or 3),
- trip_id/deadhead_id/run_event_id,
- maybe a start/end time/location (but you could get that from `trips.txt`/`deadheads.txt`/`run_events.txt` instead).

Perhaps with some tweaks something like that could even remove the need for a "pieces" concept and replace the `runs_pieces.txt` table? (Sorry if this sort of brainstorming / divergent thinking isn't useful right now.)

**Comment by safrazier17** [comment]
> > we have runs as being made up of 1 or more pieces, and we defined a piece (at least verbally) as being everything between an employee getting on a vehicle and getting off the same vehicle
> 
> I don't like the "same vehicle" restriction. On the MBTA Green Line, vehicle assignments are very ad hoc, and operators often swap vehicles between every trip (at least in reality. The schedule might satisfy the one-piece-one-block assumption but I wouldn't want to depend on it). Even at a more organized agency, if they do dropbacks, operators wouldn't end up on the same vehicle. I think of a piece as a consecutive period of time when you're getting paid for assigned work (i.e. not on break), regardless of what sorts of trips/layovers/tasks are scheduled for you during that time.

There is not an explicit restriction, however... As presently written, there is no (defined) way for a piece to extend across blocks. Because block information is being pulled from the trip/deadhead, and piece is defined from start trip/deadhead/event to end trip/deadhead/event, I would say it is currently implicit in the structure that a piece would have 0 to 1 blocks.

If a piece has more than 1 block, I'm not sure we have sufficient information to be able to model what the run/piece itself looks like.

**Comment by skyqrose** [comment]
Superseded by #51
