### ISSUE TITLE
Include service_id in runs_pieces.txt to support non-unique run_ids?

### ISSUE THREAD

**Issue by skyqrose** [cal-itp/operational-data-standard#12]
I couldn't attend the recent meeting about the ODS spec, but I watched the recording, and have some lingering questions. I hope I'm not too late for them.

In MBTA's data, two completely different runs might have the same `run_id` if they're on different services, and the unique key for a run is `(service_id, run_id)`. For example, there's a run `1234` on Saturday, and a completely unrelated run also named `1234` on Sunday.

Eddie brought this up in the recent meeting, and the conclusion reached in the meeting was that the `service_id` could be looked up through `trips.txt` in the same way that `block_id` is. However, I don't think this solution will work for me. My project will frequently need to say "Get information about Saturday's run 1234". To have to look up the service id via the trip would be difficult because `trips.txt` doesn't have a `run_id` field, and if a run is allowed to have no trips or deadheads (see #11), that lookup would be impossible. 

I'd like to advocate for adding a `service_id` column to `runs_pieces.txt`. It could be optional so that agencies who have unique run_ids don't have to worry about it, but it's already a required column in `trips.txt` and `deadheads.txt` so I don't think it'd be a burden to if it were required.

I know it's very late in the process to bring up such a big change. Sorry I only recently realized how relevant this standard would be to my project and started keeping up to date with it. Some potential workarounds if this proposal can't go through, though none are good:
- Do the roundabout lookup for runs that include a trip. (Get all rows from runs_pieces.txt with `run_id` `1234`, then look at an arbitrary trip from that run, and filter based on the arbitrary trip's `service_id`.)
- Officially add the `service_id` to `run_events.txt`, so I can do that lookup even for runs without trips.
- Include the column as a non-standard column within my own data, even if it's not officially part of the ODS.
- Encode the `service_id` into the `run_id` or the `piece_id`, and parse it out.

[Link to the spec, for convenience](https://docs.calitp.org/operational-data-standard/spec/#runs)

**Comment by safrazier17** [comment]
@skyqrose thanks for this. I think that #11 provides a compelling reason to include service_id in runs_pieces.txt. Really this is a re-inclusion as it was there in a pre-1.0.0 version. The reason it was pruned in the first place was because of the, as you mentioned, assumption that we can pull that information from our link to trips.txt. However, that link may not be reliably existent in all cases. If we have a run without trips or a block, then how are we getting that information?
