### ISSUE TITLE
When are trip_ids required in deadheads.txt?

### ISSUE THREAD

**Issue by skyqrose** [cal-itp/operational-data-standard#13]
I couldn't attend the recent meeting about the ODS spec, but I watched the recording, and have some lingering questions. I hope I'm not too late for them.

In [`deadheads.txt`](https://docs.calitp.org/operational-data-standard/spec/#deadheadstxt), `to/from_deadhead/trip_id` are conditionally required. Under what conditions are they required?

I can imagine a hypothetical deadhead that's the only trip/deadhead in its block (maybe an overnight equipment balancing move), in which case none of the four fields could have a value.

**Comment by jeffkessler-keolis** [comment]
This is good catch, and I think it stems from us missing an element in reconciling two approaches for this element.

I believe these fields should instead become **conditionally prohibited** values, whereby a `to_deadhead_id` value is prohibited when a `to_trip_id` value is defined, and vice versa. Similarly, a `from_deadhead_id` value would be prohibited when a `from_trip_id` value is defined, and vice versa.

* * *

A bit of history behind the "legislative intent" here: the original draft said deadheads could only precede or follow revenue service, but from the Commuter Rail side, we often have deadheads that turn for other distinct deadheads.

This open concept instead allows deadheads to effectively be spliced into vehicle movements whereby a vehicle goes `trip_1`, `trip_2`, `trip_3` (determined from a `block_id`), then a deadhead entry says `dh_a` is `from_trip_id=trip_3` and `to_trip_id=dh_b`, `dh_b` has `from_trip_id=dh_a` and `to_trip_id=trip_4`, which then goes to `trip_5` via its `block_id`, etc, to form the vehicle chain of `trip_1`-->`trip_2` --> `trip_3` --> `dh_a` --> `dh_b` --> `trip_4` --> `trip_5` --> …

**Comment by skyqrose** [comment]
Since `deadheads.txt` already has a `block_id` field, you could determine the order of movements based on the times in `deadhead_times.txt`, just like you have to do to order trips within a block in vanilla GTFS. If these fields were there based on the assumption that deadheads only went into trips, and that assumption is no longer held, should these fields be completely removed?

**Comment by jeffkessler-keolis** [comment]
I believe we said that's a valid approach iff the provider lists all trips and the deadheads on the same block_id, but not all providers — especially on the railroad side — provide (or wish to share) publicly-accessible block_ids, nor do all providers operate trips where the pre-deadhead and post-deadhead trips are on the same defined block. Hence the desire for a block-agnostic approach that could be implemented more widely.

**Comment by skyqrose** [comment]
Superceded by #51 , which has a new way to order deadheads within a run, and suggests removing these fields from `deadheads.txt`.
