### ISSUE TITLE
Create Past Meetings section under Resources

### ISSUE THREAD

**Issue by safrazier17** [cal-itp/operational-data-standard#17]
# Overview
We would like to have a new section where we can host information about past meetings (currently all meetings have been for the ODS Working Group, although that may change in future).

# Requirements
* Add a new section under the page created in #8 
* Add the following text to the section
> 

> | Meeting     | Date  | Description                          |
> | :---------- | :---- |:----------------------------------- |
> | [Working Group Meeting #1](https://docs.google.com/presentation/d/1ZWjaPDi5MZkWt3kzdOw1CXEGfphbeSdkenjKOAwy7aY) | 20 Jul 2021 | Confirmation of need. |
> | Stakeholder Scoping Meetings | Aug 2021 | Individual meetings with stakeholders to get detailed needs and scoping input. |
> | [Working Group Meeting #2](https://docs.google.com/presentation/d/1n4ffD1564f_r5WVZlST7w2M0FH0vW6zrQ6dQ1cagvoE) | Aug 2021 | Scope confirmation and process confirmation for spec development. |
> | [Working Group Meeting #3](https://docs.google.com/presentation/d/19TKTKTW54Vs8EeQ76kN8xAO-qFMUUTlj-LT9bYlJQXQ) - [notes](https://docs.google.com/document/d/1w2y7aHPlQ-A1ls3LDfYqolM9vhd3Z05fiNqec5Jxxd4) |  28 Sep 2021 | [Personnel Proposal](https://docs.google.com/document/d/1doswkEZ2kt6ACLHQJQ3k_jBlQGppGnU1BSkbYM8Lybw)  |
> | [Working Group Meeting #4](https://docs.google.com/presentation/d/17aNfY1duDNa_fX3ByUqarzsvHhuRsybbvaGxwCZEMZg) - [video](https://drive.google.com/file/d/1LBgMbdRb0mnO2PtVIUVq8TIiyr3tP0ly/view?usp=sharing) | 19 Oct 2021 | [Facilities Proposal](https://docs.google.com/document/d/1bUheweHg5udmBqJIJehO9g8r_JyoU6jLuicbJ8Fgag0) |
> | Working Group Meeting #5 |  16 Nov 2021 | [Runcutting, Layovers, +  Deadheads Proposal](https://docs.google.com/document/d/1PZMmyNuxOuzx3pKLehfHs9cFcfSpbpiOoUJk0x2MqLo) |
> | Working Group Meeting #6 - [video](https://drive.google.com/file/d/1P5BymBL2xXCH-sTfAwYKzUOGHqrQSjn2/view?usp=sharing) | 21 Dec 2021 | Adoption of v1 framework |
> | [Working Group Meeting #7](https://docs.google.com/presentation/d/131y4sqJ4yI0YfeXVJM7s6HMsheJOEUJRbnxO7Y5RaWw/edit?usp=sharing) - [video](https://drive.google.com/file/d/1fA8a_8YoaJOS0ZqwSKzQWDy88-T2dOTd/view?usp=sharing) | 22 Feb 2022 | Discussion of Upcoming Implementation Steps |
> | Working Group Meeting #8 - [video](https://drive.google.com/file/d/1aJ-Vbu-wFHdI01tAHH40ZCpvpawMD7Sx/view?usp=sharing) | 3 May 2022 | Reconsideration of v1 framework and adoption of 1.0.0 |

**Comment by thekaveman** [comment]
@safrazier17 - FYI the only link from above that is available publicly / anonymously is the `Personnel Proposal` - all others are asking for a Google sign in.

On that note, do we want to add links to the other meeting videos, notes, etc. where we have them?

**Comment by safrazier17** [comment]
@thekaveman good catch, I'll make a note to go through and adjust the sharing properties tomorrow. I do have it on my list to see if we have the other videos available as well. The first couple videos I think went onto Allie's zoom account before she left and I know I dl'ed them at some point but need to go and find them

**Comment by safrazier17** [comment]
Adjusted the sharing properties and also made minor textual edits to this page @thekaveman
