### ISSUE TITLE
add parent_ops_location to ops_locations.txt

### ISSUE THREAD

**Issue by BTollison** [cal-itp/operational-data-standard#47]
This proposal seeks to add an ability to nest ops_location_id's like it is possible to do with stop_id's. This is especially useful when there are multiple groups of chargers at a depot where they may have varying maximum charging speeds or availability periods.

**parent_ops_location**
- When an ops_location_id is present in this field, it is considered the parent of this ops_location_id.

**Comment by safrazier17** [comment]
This issue is closed as the functionality in ODS will now be equivalent to the functionality allowing parent-child relationships in GTFS, under proposal #55
