### ISSUE TITLE
Update About.md page copy

### ISSUE THREAD

**Issue by safrazier17** [cal-itp/operational-data-standard#9]
# Overview

We would like to change the copy for the Operational Data Standard website to remove redundancies, organize information logically, and make sure all the information is up-to-date in advance of the planned public launch of ODS. This issue contains updates for the About page (about.md).

# Requirements
* Replace existing text with following:
> # About
> 
> This website and the Operational Data Standard are maintained by [Cal-ITP](https://dot.ca.gov/cal-itp), a project of the California Department of Transportation. ODS was originally developed as a product of the Operational Data Standard Working Group, which was convened by Cal-ITP in 2021.
> 
> For information about how the Operational Data Standard was originally developed, go to the Spec Development[internal link to Spec Development page] page. To see videos of past meetings or presentations regarding the Operational Data Standard, go to the Resources[internal link to Resources page] page. For information about the Operational Data Standard Working Group, go to the Working Group[internal link to Working Group page] page.

**Comment by thekaveman** [comment]
I'm looking at the new links on this page, and have some questions/suggestions.

## Work in progress

In #10 I started implementing a _Specification_ section with pages:

* Reference
* Revision History
* Development (one of the links from this issue)

Here's a quick screenshot from the preview site:

![image](https://user-images.githubusercontent.com/1783439/165863064-bee9799e-8694-4735-be7b-063f5cd087be.png)

Does it make sense to house the Development page under _Specification_?

## Different idea

Another thought I had was to leave the _Specification_ section as:

* Reference
* Revision History

And then make _About_ be its own section containing pages:

* About.md content as updated in this Issue
* Resources (from #8)
* Spec Development
* Working Group

Could potentially even combine the last two into a single page.

**Comment by safrazier17** [comment]
@thekaveman What you have under different idea is what I was hoping to see actually. That looks great. For the Working Group page, I was hoping to put in the actual membership of the working group, whereas the Spec Development group would be the steps that were taken by that group in crafting, specifically, v 1.0
